-- Create user_activity_logs table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.user_activity_logs (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid, -- Optional, links to auth.users if available
    action_type text NOT NULL, -- e.g., 'create_lead', 'update_status', 'send_email'
    resource_type text NOT NULL, -- e.g., 'lead', 'pitch'
    resource_id text NOT NULL, -- Link to leads.id
    details jsonb DEFAULT '{}'::jsonb,
    CONSTRAINT user_activity_logs_pkey PRIMARY KEY (id)
);

-- Index for fast lookup by resource (Lead)
CREATE INDEX IF NOT EXISTS idx_activity_resource ON public.user_activity_logs(resource_id, resource_type);

-- Index for ordering
CREATE INDEX IF NOT EXISTS idx_activity_created_at ON public.user_activity_logs(created_at DESC);

-- RLS
ALTER TABLE public.user_activity_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all access for internal tool" ON public.user_activity_logs
    FOR ALL
    USING (true)
    WITH CHECK (true);
